# HAREZMİ Teması
colors:
  primary: "#2E86AB"      # Ana renk (mavi)
  secondary: "#F18F01"    # Vurgu rengi (turuncu)
  background: "#212121"   # Koyu arkaplan (logo ile uyumlu)
  text_color: "#FFFFFF"   # Beyaz metin
  accent: "#00E5E0"       # Logo turkuaz rengi
  light_bg: "#F8F9FA"     # Açık arkaplan

fonts:
  title: "Helvetica"
  body: "Arial"

styles:
  figure.figsize: [11, 8]
  font.size: 10
  axes.titlesize: 14
  axes.labelsize: 12